repository: SwedbankPay/developer.swedbankpay.com
remote_theme: SwedbankPay/swedbank-pay-design-guide-jekyll-theme
exclude: ["Gemfile*", "Rakefile"]
plugins:
  - "jekyll-github-metadata"
defaults:
  - values:
      layout: default
      design_guide:
        base_url: https://design.swedbankpay.com
        version_url: https://design.swedbankpay.com/v/4.1.0
      topbar:
        navigation:
        - url: /page1
          title: Top 1
        - url: /page2
          title: Top 2
      sidebar:
        search:
          enabled: true
        navigation:
          - title: Group 1
            items:
            - url: /page1
              title: Side 1
            - url: /page2
              title: Side 2
          - title: Group 2
            items:
            - url: /page1
              title: Side 3
            - url: /page2
              title: Side 4
