name: Build and push to gh-pages

on:
  push:
    branches:
    - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NullableInt/jekyll-builder-for-github-pages-action@master
        with:
          secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
          git_committer_email: dev@payex.com
          git_committer_name: payex-dev
          gh_pages_publishing_source: gh-pages
        env:
          DEBUG: "true"
          GITHUB_ACTOR: payex-dev
          JEKYLL_GITHUB_TOKEN : ${{ secrets.GH_PAGES_TOKEN }}
